import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>SimbirSoft</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1>Click!</h1>
                <div>
                    <a target="_blank" href="https://t.me/rlukoyanov">
                        Telegram: @rLukoyanov
                    </a>
                </div>
                <div>
                    <a target="_blank" href="https://github.com/rLukoyanov">
                        gitHub: @rLukoyanov
                    </a>
                </div>
                <div>
                    <a target="_blank" href="https://github.com/rLukoyanov/simbirSoft">
                        gitHub: this project
                    </a>
                </div>
                
            </main>
        </>
    );
}
